ace:
  filename: ace.gif
  response: Sorry for the delay, Ace! Oooooooh, wee!
alrighty:
  filename: alrighty.jpg
  response: Allllllllllllllllllllllllllllllllllllrighty, then! Ooh, wee!
ass:
  filename: ass.gif
  response: Ooh, wee! Certainly sounds like ass to me!
bitch:
  filename: bitch.jpg
  response: Ooh, wee! Someone forgot to take their bitch pills today!
blyat:
  filename: blyat.gif
  response: RUSH B, CYKA BLYAT! OOOOOOOH, WEEEEE!
bobross:
  filename: bobross.jpg
  response: Ooh, wee! Looks like we're gonna have a happy little accident!
brilliant:
  filename: brilliant.jpg
  response: BREEEEEEEEEEEEEEEEEEEEEEEEEEELIANT!
button:
  filename: button.gif
  response: Ooh, wee! Press the damn button and let's do this!
butts:
  filename: butts.gif
  response: Hold on to your butts! Ooh, wee!
cage:
  filenames:
  - cage1.gif
  - cage2.gif
  - cage3.gif
  - cage4.gif
  - cage5.gif
  - cage6.gif
  response: Ooh, wee! Time to pay homage to the Internet's One True God!
closed:
  filename: sorryfolks.jpg
  response: Park's closed, bitch! Ooh, wee!
coldone:
  filename: coldone.jpg
  response: The Oneitude is directly proportional to the Colditude of the One! Ooh, wee!
cool:
  filename: coolstory.jpg
  response: Talk about a cool story, bro! Ooh, wee!
damage:
  filename: damage.png
  response: OOH, WEE! THAT'S A LOT OF DAMAGE!
dance:
  filename: dance.gif
  response: Ooh, wee! Pardon me while I do a victory dance for you!
danger:
  filename: danger.jpg
  response: Danger, Will Robinson! Danger! Ooh, wee!
dialedin:
  filename: dialedin.jpg
  response: Ooh, wee! Looks like SOMEBODY is dialed in!
dog:
  filename: dog.gif
  response: Ooh, wee! Chris wants you to see this gif of a dog!
doge:
  filename: doge.jpg
  response: Much meme. Very response. Such bot. Wow. Ooh, wee!
drumroll:
  filename: drumroll.gif
  response: Can I get a drumroll, please? It's time to find out what everyone thinks of that! Ooh, wee!
dumb:
  filename: dumb.png
  response: Ooh, wee! Looks like you had a _great_ suggestion! Let's think about that one!
engineer:
  filename: engineer.png
  response: Trust me, I'm an engineer! Ooh, wee!
ettu:
  filename: ettu.jpg
  response: Ooh, wee! Et tu? Cogitavi in ​​qua sumus, amici! Bitch.
f1fail:
  filename: f1fail.gif
  response: Ooh, wee! Red Bull is definitely gonna win the Constructor's Championship this year, right?
fail:
  filename: fail.jpg
  response: That was certainly a fail, wasn't it, folks? Ooooooh, wee!
fine:
  filename: fine.gif
  response: Sometimes it's just easier to agree with someone just to shut them up! Ooh, wee!
fired:
  filename: fired.gif
  response: Ooh, wee! Looks like the Jitz found out, didn't he?
fireworks:
  filename: fireworks.gif
  response: Ooh, wee! Time for a celebration! Time to celebrate with an ass-kicking!
ffs:
  filename: ffs.gif
  response: Ooh, wee! That didn't quite go as planned!
fu:
  filename: fu.jpg
  response: Ooh, wee! Someone needs a three-finger salute!
fu2:
  filename: fu2.jpg
  response: Ooh, wee! Someone else needs a three-finger salute, too!
fuckmas:
  filename: fuckmas.jpg
  response: Ooh, wee! Ho, ho ho, motherfuckers!
gay:
  filenames:
  - gay1.jpg
  - gay2.jpg
  - gay3.jpg
  - gay4.jpg
  - gay5.jpg
  - gay6.jpg
  response: Ooh, wee! Here's how gay that shot was!
goodshow:
  filename: goodshow.jpg
  response: Ooh, wee! Eetsa gooda show!
hack:
  filename: hack.gif
  response: HACK THE PLANET! HAAAAACK THE PLAAAAANET!!!
hacking:
  filename: hacking.gif
  response: I'm hacking here! Doing important stuff! Serious business! Ooh, wee!
halp:
  filename: halp.jpg
  response: Ooh, wee! Sounds like somebody is in a bit over their head!
hank:
  filename: hank.gif
  response: All the propane accessories in the world can't hide your bullshit! Ooh, wee!
hattip:
  filename: hattip.gif
  response: Ooh, wee! I tip my hat to you, sir!
high:
  filename: high.gif
  response: Ooh, wee! I think that brownie had something in it!
hitit:
  filename: hitit.gif
  response: Ooh, wee! Are you on a mission from God?
idgaf:
  filename: idgaf.gif
  response: On a scale of one to I don't give a fuck, I don't give a fuck! Ooh, wee!
ight:
  filename: ight.jpg
  response: Time to get the fuck out of Dodge! Ooh, wee!
igotthis:
  filename: igotthis.jpg
  response: Ooh, wee! SOMEONE needs to chill the fuck out!
ihateyou:
  filename: ihateyou.jpg
  response: Ooh, wee! Someone's pissed somebody off, tonight!
impossibru:
  filename: impossibru.jpg
  response: Ooh, wee! Eetsa Subaru...IMPOSSIBRU!
latifi:
  filename: latifi.jpg
  response: Ooh, wee! Looks like Latifi over there is playing the long game!
letsgo:
  filename: letsgo.gif
  response: Ooh, wee! Someone needs to take their goddamn shot, already!
light:
  filename: thelight.gif
  response: Ooh, wee! Someone has seen the light!
list:
  filename: thelist.jpg
  response: Ooh, wee! You know what happens to people who type this command? YOU JUST MADE THE LIST!
more:
  filename: more.jpg
  response: Ooh, wee! Sounds like the shots just aren't gonna stop!
neener:
  filename: neener.jpg
  response: Neener neener foo foo! I iz cute so stfu! Ooh, wee!
nice:
  filename: nice.gif
  response: Ooh, wee! That was pretty nice!
"no":
  filename: no.png
  response: The word no has two letters in it and you still can't understand what it means! Ooooooh, wee!
nofucks:
  filename: nofucks.jpg
  response: Ooh, wee! On a scale of 1 to your mom's a whore, I really don't give a fuck!
nope:
  filename: nope.gif
  response: Denied, bitch! Oooooooooh, wee!
notgood:
  filename: notgood.jpg
  response: Ooh, wee! That last shot was notta so good!
notsorry:
  filename: notsorry.gif
  response: Sorry, not sorry! Ooh, wee!
nowai:
  filename: nowai.jpg
  response: Someone had to see the owl memes all the way through! Ooh, wee!
nuke:
  filename: nuke.gif
  response: The time-honored traditional way to give someone the middle finger in Shellshock! Oooooooooh, wee!
ole:
  filename: ole.jpg
  response: Ooh, wee! Time for a fiesta!
oof:
  filename: oof.gif
  response: Ooh, wee! That was oof-worthy!
oohwee:
  filename: oohwee.png
  response: "OOOOOOOOOOOOOOOOOOOOOOOOOOH,\nWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE!"
oops:
  filename: oops.gif
  response: Ooh, wee! Looks like someone made an oopsie-woopsies!
opinion:
  filename: opinion.png
  response: Ooh, wee! Here's what you can do with your opinion!
orly:
  filename: orly.jpg
  response: Oh reeeeeeeeeeeeeeeally? Ooh, wee!
owls:
  filename: owls.gif
  response: Ooh, wee! We have a lazy asshole here who doesn't feel like typing out all the owl memes!
poop:
  filenames:
  - poop1.gif
  - poop2.gif
  - poop3.gif
  - poop4.gif
  - poop5.gif
  - poop5.gif
  response: Ooh, wee! Aren't we just the bastion of maturity?
race:
  filename: race.gif
  response: Ooh, wee! I feel the need! The NEED...for SPEED! Just watch out for danger to manifold!
rad:
  filename: rad.gif
  response: Ooh, wee! That was totally rad, bro! You're cool!
safety:
  filename: safety.jpg
  response: Ooh, wee! Gotta have a meme devoted to the F1 safety car, the undefeated champion that has never been passed on track!
sand:
  filename: sand.jpg
  response: Teaching sand to think was a mistake, wasn't it? Ooh, wee!
sarcasm:
  filename: sarcasm.gif
  response: Ooh, wee! My super bot powers detect a hint of sarcasm in the air!
scared:
  filename: scared.gif
  response: Ooh, wee! You got me quakin' in my boots over here!
scotch:
  filename: scotch.jpg
  response: Ooh, wee! I love scotch! Scotchy-scotch-scotch!
seal:
  filename: seal.gif
  response: If you see the seal moving, it's your imagination! Ooh, wee!
shakira:
  filename: shakira.mp4
  response: Ooh, wee! I hear her hips don't lie!
shoo:
  filename: shoo.gif
  response: Go 'way. Shoo.
shutup:
  filename: shutup.gif
  response: Ooh, wee! Someone needs to SHUUUUUUUUUUUUUT UUUUUUUUUUUUUUUP!
slap:
  filenames:
  - slap.gif
  - batslap.gif
  response: Ooh, wee! Someone is gonna need their shit slapped!
sleep:
  filename: sleep.png
  response: Ooh, wee! Looks like somebody needs their beauty sleep!
smile:
  filename: smile.gif
  response: :-D
sorry:
  filename: sorry.png
  response: 'Ooh, wee! Let me guess: you didn''t mean to shoot him, did you?'
stfu:
  filename: stfu.jpg
  response: Ooh, wee! Someone is running their mouth and really need to give it a break!
thumbsup:
  filename: thumbsup.gif
  response: Who has two thumbs and approves? THIS GUY! OOOH, WEE!
torvalds:
  filename: torvalds.jpg
  response: Ooh, wee! Even Linus Torvalds hates you!
triggered:
  filename: triggered.gif
  response: Ooh, wee! Someone better retreat to their safe space right away!
twitch:
  filename: hank.gif
  response: My eye twitches so my hands don't choke you out! Ooh, wee!
victory:
  filename: victory.gif
  response: Ooh, wee! I love a good victory this time of year!
waiting:
  filename: waiting.gif
  response: Ooh, wee! Someone's taking their sweet-ass time today!
waldo:
  filename: waldo.jpg
  response: Ooh, wee! I found that motherfucker!
wam:
  filename: wam.jpg
  response: Um...I was wondering, wat's the wecommended amount of dedodaded wam I should have for a server? Ooh, wee!
welp:
  filename: welp.jpg
  response: Ooh, wee! Sounds like the match isn't going someone's way!
whore:
  filename: whore.png
  response: Ooh, wee! Someone's a whorish whore who should go back to their home on whore island!
win:
  filename: win.gif
  response: Ooh, wee! That sure looks like a win to me!
wink:
  filename: wink.gif
  response: ;-D Ooh, wee!
wondrous:
  filename: wondrous.gif
  response: "Such a wondrous... *awkwardly long pose* ...thing! Ooh, wee!"
wtf:
  filename: wtf.gif
  response: Ooh, wee! What the fuck?
xp:
  filename: drevil.gif
  response: "Ooh, wee, Scott! That was...\nONE MEEELLION XP! That's a lot of frickin' XP!"
yarly:
  filename: yarly.jpg
  response: Ya really, bitch. Ooh, wee!
yee:
  filename: yee.gif
  response: YEEEEEEEEEEEEEEE!
yomomma:
  filenames:
  - yomomma1.jpg
  - yomomma2.jpg
  - yomomma3.jpg
  - yomomma4.jpg
  - yomomma5.jpg
  - yomomma6.jpg
  - yomomma7.jpg
  - yomomma8.jpg
  - yomomma9.jpg
  - yomomma10.jpg
  - yomomma11.jpg
  - yomomma12.jpg
  - yomomma13.jpg
  - yomomma14.jpg
  - yomomma1.png
  - yomomma2.png
  - yomomma3.png
  - yomomma1.gif
  response: Ooh, wee! Time to make fun of yo momma!
youdontsay:
  filename: youdontsay.gif
  response: OOOH, WEE! YOU DON'T SAY?????
youlose:
  filename: youlose.jpg
  response: Under section 37B of a contract signed by you, your mom's a whore! You lose! Ooh, wee!
yourmom:
  filename: yourmom.png
  response: Ooh, wee! That's not what YOUR MOM said last night!
  