main:
  title: "Meet Mr. Poopybutthole!\nOoooooooooooh, wee!"
  description: |-2
    I am a handy-dandy bot that is a one-stop meme shop! My memes are split into three categories:

    **Commands** - These are commands I accept that start with a `!`, such as `!oohwee` or `!ole`!

    **Listeners** - I'll say these when you say the right things in your messages, such as `adonis` `superman`! They'll pop up even if you don't expect them to!

    **Snowflake Mode** - A super-special troll mode for all you special snowflakes out there! Type `!snowflake on` to start the party!

    **Help Topics**
  image: True
  fields:
    commands:
      name: "!help commands"
      value: List all the commands I support!
    listeners:
      name: "!help listeners"
      value: List all my listeners and their trigger words!
    snowflake:
      name: "!help snowflake"
      value: Get more details on how Snowflake Mode works! Ooh, wee!
    fortune:
      name: "!help fortune"
      value: How to get your fortune!
snowflake:
  title: Mr. Poopybutthole Snowflake Mode
  description: |-2
    Sometimes, you just gotta troll someone, right? Snowflake Mode does just that to this server's certain special snowflakes!

    Turning it on will make me respond to *all* the snowflake's messages and even change their nicknames!

    I'll keep going until you retreat to your safe space or someone turns off Snowflake Mode!

    **Snowflake Mode Commands**
  image: False
  fields:
    snowflake:
      name: "!snowflake` `!snowflake status` `!snowflakes"
      value: Get the status on Snowflake Mode! See whether it is enabled and who is in their safe space!
    on:
      name: "!snowflake on"
      value: Turns on Snowflake Mode! I'll start annoying anyone that hasn't retreated to their safe space!
    off:
      name: "!snowflake off"
      value: Turns off Snowflake Mode for everyone! Can only be done by non-snowflakes or snowflakes already in their safe space!
    force:
      name: "!snowflake force"
      value: Turns on Snowflake Mode for everyone, even those already in their safe space! Can only be run by fellow snowflakes, though!
    safespace:
      name: "!snowflake safespace"
      value: Retreat to your safe space...I'll leave you alone after you use this command!
    brave:
      name: "!snowflake brave"
      value: Emerge from your safe space...you brave snowflake you!
    safephrase:
      name: "Saying the Safe Phrase"
      value: Another way to retreat to your safe space... Type `!snowflake` to see the current safe phrase!
fortune:
  title: Mr. Poopybutthole's Fortune Service
  description: "Mr. Poopybutthole now works with the Eagleworld API, which can give you your fortune! Here are the different options you can use:"
  image: False
  fields:
    plain:
      name: "!fortune` or `!fortune plain"
      value: Just get a plain, simple fortune! Best for mobile Discord users!
    cow:
      name: "!fortune cow"
      value: Get your fortune, but have a cow say it to you! Very Debian apt-like!
    tux:
      name: "!fortune tux"
      value: Get your fortune from Tux, the Linux penguin! Ooh, wee!
    more:
      name: "More to come"
      value: The Eagleworld API is just getting started, so more options will be available soon!
commands:
  title: Mr. Poopybutthole Commands
  description: Here's all the general meme commands I support! Ooh, wee!
  image: False
listeners:
  title: Mr. Poopybutthole Listeners
  description: Here's all the listeners I support, and the matches that trigger them! Ooh, wee!
  image: False
