adonia:
  filename: adonia.jpg
  matches:
  - adonia
  - superwoman
  response: Ooh, wee! I'm pretty sure that's something an adonia superwoman would do!
adonis:
  filename: adonis.jpg
  matches:
  - adonis
  - superman
  response: Ooh, wee! I'm pretty sure that's something an adonis superman would do!
awful:
  filename: awful.gif
  matches:
  - awful
  - horrible
  response: Ooh, wee! On a scale of one to your mom's a whore, that sucked donkey balls!
badbot:
  filename: badbot.jpg
  matches:
  - bad bot
  response: Ooh wee! You're a salty little fuck, aren't you?
bitch:
  filename: bitch.gif
  matches:
  - bitch
  - please
  response: Bitch, please! You don't want to fuck with this! Ooh, wee!
bork:
  filename: bork.gif
  matches:
  - bork
  - lazer
  response: IMMA FIRIN' MAH BORK LAZER!!! OOOOOOOOOH, WEEEEE!
bruh:
  filename: bruh.gif
  matches:
  - bruh
  response: Ooh wee, bruh...
chris:
  filenames:
  - chris.jpg
  - chris2.jpg
  - chris3.jpg
  - okay.gif
  - okay.gif
  - okay.gif
  matches:
  - chris
  response: Ooh, wee!
chrome:
  filename: chrome.png
  matches:
  - chrome
  - ram
  response: Ooh, wee! Someone must really hate their RAM!
clever:
  filename: clever.gif
  matches:
  - clever
  - girl
  response: Ooh, wee! That there's a clever girl!
dinodna:
  filename: dinodna.gif
  matches:
  - bingo
  - dino
  - dna
  response: BINGO! Dino DNA! Ooooooooh, wee!
dumbass:
  filename: dumbass.gif
  matches:
  - dumb
  - dumbass
  - dumass
  response: Ooh, wee! Good job there, dumbass!
fucks:
  filename: fucks.jpg
  matches:
  - guys
  - shut up
  - stfu
  - fuck
  response: Ooh, wee! Someone needs to shut their fucks!
garfielf:
  filename: garfielf.png
  matches:
  - garfielf
  - garfield
  - jon
  - god
  - nermal
  response: |-2
    Ooh, wee, Jon. You stupid fuck. How could you...Jon?
    You were my amigo, Jon. My muchaho, my compadre! Jon...
    ...make me God! Being a celestial body is exhausting!
    I'm gonna eat everything!
goodbot:
  filename: goodbot.jpg
  matches:
  - good bot
  response: You like me! You really like me! Oooooooooh, wee!
goodjob:
  filename: goodjob.gif
  matches:
  - job
  - jorb
  response: _CLAP_ _CLAP_ _CLAP_ Good job, dumbass! Ooh, wee!
godlonso:
  filename: godlonso.gif
  matches:
  - fernando
  - alonso
  - godlonso
gud:
  filename: gud.gif
  matches:
  - dis
  - gud
  response: Ooh, wee! Dis gun b gud, isn't it?
hackerman:
  filename: hackerman.gif
  matches:
  - kung
  - fury
  - hackerman
  response: Grab your power glove, it's time to hack the planet! Ooh, wee!
hotsack:
  filename: hotsack.png
  matches:
  - hot
  - sack
  - lunch
  response: Ooh, wee! I think somebody ordered the hot sack lunch!
help:
  matches:
  - help
  - halp
  - pls
  - plz
  response: Ooh, wee! If you want some help from me, you should probably try the `!help` command!
hmmm:
  filename: hmmm.gif
  matches:
  - hmmm
  - huh
  response: Hmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm?
ladida:
  filename: ladida.jpg
  matches:
  - ladida
  - lah
  - dee
  - frickin
  - dah
  response: Ooh, wee! Well LA DI FRICKIN' DA!
look:
  filename: ಠ_ಠ.gif
  matches:
  - ._.
  - ಠ_ಠ
nukem:
  filename: nukem.png
  matches:
  - balls
  - duke
  - nukem
  - steel
  response: Ooh, wee! I've got balls of steel!
okay:
  filename: okay.gif
  matches:
  - okay
  - whatever
  response: Okay...whatever you say there, big guy! Sure!
orange:
  filename: orangewhip.gif
  matches:
  - orange
  - whip
  response: Who want's an orange whip? Ooh, wee!
peloton:
  filename: peloton.jpg
  matches:
  - peloton
  - pelaton
  response: Ooh, wee! Nobody's laughing at that Peloton ad anymore, are they?
peter:
  filenames:
  - peter.jpg
  - peter2.jpg
  - peter3.jpg
  - peter4.jpg
  - peter5.jpg
  - peter6.jpg
  matches:
  - peter
  response: Ooh, wee!
racist:
  filenames:
  - racist1.gif
  - racist2.gif
  - waisis1.gif
  - waisis2.gif
  matches:
  - racist
  - waisis
  response: Ooh, wee! That's pretty racist, bro!
rob:
  filenames:
  - rob.jpg
  - rob2.jpg
  - rob3.jpg
  - rob4.jpg
  matches:
  - rob
  response: Ooh, wee! I hear Rob doesn't miss!
rubber:
  filename: rubber.gif
  matches:
  - dust
  - rubber
  response: Let's burn some dust here. Eat my rubber! Ooh, wee!
shit:
  filename: shit.gif
  matches:
  - shit
  - shiat
  - crap
  - poop
  response: Someone's talking shit...LITERALLY! Ooooooh, wee!
spicyboi:
  filename: spicyboi.jpg
  matches:
  - spicy
  - boi
  - boy
  response: Ooh, wee! That there's a spicy, spicy boi!
suez:
  filename: suez.gif
  matches:
  - suez
  - canal
  response: Ooh, wee! Gotta hit that 20,000 container drift, yo!
sup:
  filename: sup.gif
  matches:
  - sup
  - what's up
  - whats up
  response: Heeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeyyyyyyyy! Ooh, wee!
twisted:
  filename: m16.jpg
  matches:
  - m16
  - twisted
  - sister
  - guitar
  response: "OOH, WEE! I CARRIED AN M16 AND YOU...\nYOU CARRY THAT, THAT...GUITAR!!!"
